### ISSUE TITLE
Avoid relying on `dm::select()`

### ISSUE THREAD

**Issue by krlmlr** [agroscope-ch/srppp#3]
Reexporting dplyr generics in dm was a mistake: every time we do `?select`, an ugly disambiguation shows in the help pane.

I'd like to remove the reexports in a future release of dm. This will break the vignettes in this package. What's a good timeline for an update of srppp that avoids relying on dm reexporting dplyr?

Upstream: https://github.com/cynkra/dm/pull/2245

**Comment by krlmlr** [comment]
I'll also check what happens if dm _depends_ on dplyr.

**Comment by jranke** [comment]
Thanks for coming over to mention this! Feel free to remove the reexport, I am frequently working on the package, so can accomodate a necessary change in the vignette when needed.
